### PR TITLE
Add support for unreleased Hello Kitty Pocket Camera rom

### PR DESCRIPTION
**Pull request by cristofercruz**
An unreleased Hello Kitty variant of the Pocket Camera rom has been leaked and it's unlike any of the other roms. Frames are not stored in the same consistent way. Tile data and tile maps are all over the rom. I added an array with pre-defined offsets for each frame and map and retrieve those when the rom is the Hello Kitty one (identified by reading the embedded ROM title).

### CODE REVIEW

**Comment by jkbenaim** [comment]
This looks good! Let me take a closer look tonight before I smash the merge butotn.

**Comment by cristofercruz** [comment]
Any feedback if things can be done in a better way is appreciated also.

**Comment by jkbenaim** [comment]
LGTM, thank you!

**Comment by jkbenaim** [comment]
Hey-- I originally wrote this program a long time ago. To my eyes now, it looks pretty rough. I'm going to take a stab at improving it. As a result, some of your changes might get undone. Please don't be offended if that happens. I just need to scratch this itch :) And thanks again for the HK camera support! I really appreciate it.

**Comment by cristofercruz** [comment]
No worries, glad I could chip in even if just for a bit 😉

**Pull request merged**
